# Generated by Django 3.0.2 on 2020-02-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psql01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Href',
        ),
    ]
