# Generated by Django 3.0.2 on 2020-02-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('psql01', '0002_delete_href'),
    ]

    operations = [
        migrations.CreateModel(
            name='testtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'testtable01',
            },
        ),
    ]
